package com.ltw.cinema.gui.casier;

import com.ltw.cinema.api.dto.BookingDto;
import com.ltw.cinema.api.feign.BookingClient;
import com.ltw.cinema.gui.CinemaGUIApplication;
import com.ltw.cinema.gui.desktop.gui.CasierGUI;
import javafx.util.Pair;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * @author uid22489
 */
public class CasierMainPanel extends JPanel {

    private static CasierMainPanel singletonInstance;
    private CasierWorkPanel casierWorkPanel;

    /**
     * Creates new form JPanel1
     */
    private CasierMainPanel() {
        initComponents();

        casierWorkPanel = new CasierWorkPanel();
        interfacePanel.setLayout(new BorderLayout());
        interfacePanel.add(casierWorkPanel, BorderLayout.CENTER);
    }

    public static CasierMainPanel getInstance() {
        if (Objects.isNull(singletonInstance)) {
            singletonInstance = new CasierMainPanel();
        }

        return singletonInstance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        cinemaLabel = new javax.swing.JLabel();
        administratorLabel = new javax.swing.JLabel();
        cumparaButton = new javax.swing.JButton();
        numeFilmLabel = new javax.swing.JLabel();
        dataLansareLabel = new javax.swing.JLabel();
        detaliiFilmScroll = new javax.swing.JScrollPane();
        detaliiFilmText = new javax.swing.JTextArea();
        pretLabel = new javax.swing.JLabel();
        tipFilmLabel = new javax.swing.JLabel();
        interfacePanel = new javax.swing.JPanel();
        windowPanel = new javax.swing.JPanel();
        exitLabel = new javax.swing.JLabel();
        minimizeLabel = new javax.swing.JLabel();

        setBackground(new Color(179, 165, 201));

        menuPanel.setBackground(new Color(54, 33, 89));
        menuPanel.setAlignmentX(0.0F);
        menuPanel.setAlignmentY(0.0F);

        cinemaLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cinemaLabel.setForeground(Color.white);
        cinemaLabel.setText("MovieTime");
        cinemaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cinemaLabelMouseClicked(evt);
            }
        });

        administratorLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        administratorLabel.setForeground(Color.white);
        administratorLabel.setText("Casier");

        cumparaButton.setBackground(new Color(0, 0, 0));
        cumparaButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cumparaButton.setText("Cumpără");
        cumparaButton.setEnabled(false);
        cumparaButton.setOpaque(false);
        cumparaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cumparaButtoncumparaActionPerformed(evt);
            }
        });

        numeFilmLabel.setBackground(new Color(85, 65, 118));
        numeFilmLabel.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        numeFilmLabel.setForeground(Color.white);
        numeFilmLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numeFilmLabel.setText("CEVA");
        numeFilmLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        numeFilmLabel.setOpaque(true);

        dataLansareLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        dataLansareLabel.setForeground(Color.white);
        dataLansareLabel.setText("dataLansare");

        detaliiFilmScroll.setBorder(null);

        detaliiFilmText.setEditable(false);
        detaliiFilmText.setBackground(new Color(54, 33, 89));
        detaliiFilmText.setColumns(20);
        detaliiFilmText.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        detaliiFilmText.setForeground(new Color(255, 255, 255));
        detaliiFilmText.setLineWrap(true);
        detaliiFilmText.setRows(5);
        detaliiFilmText.setText("descriere\n");
        detaliiFilmText.setWrapStyleWord(true);
        detaliiFilmText.setBorder(null);
        detaliiFilmText.setCaretColor(new Color(54, 33, 89));
        detaliiFilmText.setHighlighter(null);
        detaliiFilmScroll.setViewportView(detaliiFilmText);

        pretLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pretLabel.setForeground(Color.white);

        tipFilmLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        tipFilmLabel.setForeground(Color.white);
        tipFilmLabel.setText("Tip_Film");

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
                menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(menuPanelLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(administratorLabel)
                                        .addComponent(cinemaLabel))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                                .addContainerGap(27, Short.MAX_VALUE)
                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                                                .addComponent(pretLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cumparaButton)
                                                .addGap(20, 20, 20))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(dataLansareLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                                                        .addComponent(tipFilmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addContainerGap()))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(menuPanelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(detaliiFilmScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(numeFilmLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
                menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(menuPanelLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(cinemaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(administratorLabel)
                                .addGap(28, 28, 28)
                                .addComponent(numeFilmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tipFilmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dataLansareLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(detaliiFilmScroll)
                                .addGap(18, 18, 18)
                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cumparaButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(pretLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23))
        );

        interfacePanel.setBackground(new Color(255, 255, 255));
        interfacePanel.setAlignmentX(0.0F);
        interfacePanel.setAlignmentY(0.0F);
        interfacePanel.setMinimumSize(new java.awt.Dimension(450, 300));
        interfacePanel.setPreferredSize(new java.awt.Dimension(450, 300));

        javax.swing.GroupLayout interfacePanelLayout = new javax.swing.GroupLayout(interfacePanel);
        interfacePanel.setLayout(interfacePanelLayout);
        interfacePanelLayout.setHorizontalGroup(
                interfacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        interfacePanelLayout.setVerticalGroup(
                interfacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 455, Short.MAX_VALUE)
        );

        windowPanel.setBackground(new Color(179, 165, 201));

        exitLabel.setBackground(new Color(0, 0, 0));
        exitLabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        exitLabel.setText("X");
        exitLabel.setToolTipText("");
        exitLabel.setAlignmentY(0.2F);
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitLabelMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLabelMouseExited(evt);
            }
        });

        minimizeLabel.setBackground(new Color(0, 0, 0));
        minimizeLabel.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        minimizeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizeLabel.setText("-");
        minimizeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLabelMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeLabelMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout windowPanelLayout = new javax.swing.GroupLayout(windowPanel);
        windowPanel.setLayout(windowPanelLayout);
        windowPanelLayout.setHorizontalGroup(
                windowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(windowPanelLayout.createSequentialGroup()
                                .addGap(0, 28, Short.MAX_VALUE)
                                .addComponent(minimizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(exitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        windowPanelLayout.setVerticalGroup(
                windowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(windowPanelLayout.createSequentialGroup()
                                .addGroup(windowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(exitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(minimizeLabel))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 611, Short.MAX_VALUE)
                                                .addComponent(windowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(interfacePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(windowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(interfacePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLabelMouseClicked

    private void exitLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseEntered
        exitLabel.setForeground(Color.RED);
    }//GEN-LAST:event_exitLabelMouseEntered

    private void exitLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseExited
        exitLabel.setForeground(Color.BLACK);
    }//GEN-LAST:event_exitLabelMouseExited

    private void minimizeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLabelMouseClicked
        CinemaGUIApplication.getContext().getBean(CasierGUI.class).setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minimizeLabelMouseClicked

    private void minimizeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLabelMouseEntered
        minimizeLabel.setForeground(new Color(49, 114, 178));
    }//GEN-LAST:event_minimizeLabelMouseEntered

    private void minimizeLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLabelMouseExited
        minimizeLabel.setForeground(Color.BLACK);
    }//GEN-LAST:event_minimizeLabelMouseExited

    private void cinemaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cinemaLabelMouseClicked
    }//GEN-LAST:event_cinemaLabelMouseClicked

    private void cumparaButtoncumparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cumparaButtoncumparaActionPerformed
        //Trebuie stearsa rezervarea, si inlocuita cu una permanenta
        if (!" ".equals(CasierWorkPanel.emailList.getSelectedItem())) {

            CinemaGUIApplication.getContext()
                    .getBean(BookingClient.class)
                    .deleteByEmailAndScheduleId(CasierWorkPanel.emailList.getSelectedItem().toString(), CasierWorkPanel.currentScheduleDto.getId(), CasierGUI.getToken());
            JOptionPane.showMessageDialog(this, "Rezervare stearsă cu succes!",
                    "Info", JOptionPane.INFORMATION_MESSAGE);

            //TODO 500
            //JOptionPane.showMessageDialog(this, "Nu s-a putut sterge rezervarea!",
            //"Error", JOptionPane.ERROR_MESSAGE);
        }

        List<BookingDto> newBookingDtos = new ArrayList<>();

        for (Pair<Integer, Integer> selectedSpot : CasierWorkPanel.selectedSpots) {
            Integer row = selectedSpot.getKey();
            Integer column = selectedSpot.getValue();
            Optional<BookingDto> bookingDto = newBookingDtos.stream()
                    .filter(e -> e.getRow().equals(row.shortValue()))
                    .findFirst();

            if (!bookingDto.isPresent()) {
                BookingDto newBookingDto = new BookingDto(null, "default@cinema.ro", row.shortValue(), column.toString(), CasierWorkPanel.currentScheduleDto);

                newBookingDtos.add(newBookingDto);
            } else {
                bookingDto.get().setColumns(bookingDto.get().getColumns() + "," + column);
            }
        }

        CinemaGUIApplication.getContext().getBean(BookingClient.class).save(newBookingDtos, CasierGUI.getToken());
        JOptionPane.showMessageDialog(this, "Operațiune realizată cu succes!",
                "Succes", JOptionPane.INFORMATION_MESSAGE);
        //JOptionPane.showMessageDialog(MainGUI.currentFrame, "A aparut o eroare la server. Nu s-a putut face inserarea!\nVa rugam reincercati!",
        //                    "Error", JOptionPane.ERROR_MESSAGE);
        //TODO 500

        int selectedEmailIndex = CasierWorkPanel.emailList.getSelectedIndex();
        if (selectedEmailIndex != 0) {
            CasierWorkPanel.emailList.setSelectedIndex(0);
            CasierWorkPanel.emailList.removeItemAt(selectedEmailIndex);

            CasierWorkPanel.emailList.validate();
            CasierWorkPanel.emailList.revalidate();
        }

        casierWorkPanel.populateSala(" ");
        cumparaButton.setEnabled(false);
    }//GEN-LAST:event_cumparaButtoncumparaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel administratorLabel;
    private javax.swing.JLabel cinemaLabel;
    public static javax.swing.JButton cumparaButton;
    public static javax.swing.JLabel dataLansareLabel;
    private static javax.swing.JScrollPane detaliiFilmScroll;
    public static javax.swing.JTextArea detaliiFilmText;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JPanel interfacePanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel minimizeLabel;
    public static javax.swing.JLabel numeFilmLabel;
    public static javax.swing.JLabel pretLabel;
    public static javax.swing.JLabel tipFilmLabel;
    private javax.swing.JPanel windowPanel;
    // End of variables declaration//GEN-END:variables
}
