/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ltw.cinema.gui.desktop.gui;

import com.ltw.cinema.api.dto.UserDto;
import com.ltw.cinema.api.feign.UserClient;
import com.ltw.cinema.api.types.UserRole;
import com.ltw.cinema.gui.CinemaGUIApplication;

import javax.swing.*;
import java.awt.*;

/**
 * @author Bakmy
 */
@SuppressWarnings("serial")
public class LoginGUI extends JFrame {
    /**
     * Creates new form LoginGUI
     */
    public LoginGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        signInButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        windowPanel = new javax.swing.JPanel();
        exitLabel = new javax.swing.JLabel();
        minimizeLabel = new javax.swing.JLabel();
        signUpButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new Color(54, 33, 89));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new Color(255, 255, 255));
        jLabel1.setText("username");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 60, 25));

        passwordField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 150, 25));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new Color(255, 255, 255));
        jLabel2.setText("password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 60, 25));

        usernameField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        usernameField.setMinimumSize(new java.awt.Dimension(10, 20));
        usernameField.setPreferredSize(new java.awt.Dimension(10, 20));
        jPanel1.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 150, 25));

        signInButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        signInButton.setText("Autentifică-te");
        signInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInButtonActionPerformed(evt);
            }
        });
        jPanel1.add(signInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new Color(255, 255, 255));
        jLabel3.setText("Bun venit!");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        windowPanel.setBackground(new Color(54, 33, 89));

        exitLabel.setBackground(new Color(0, 0, 0));
        exitLabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        exitLabel.setForeground(new Color(255, 255, 255));
        exitLabel.setText("X");
        exitLabel.setToolTipText("");
        exitLabel.setAlignmentY(0.2F);
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitLabelMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLabelMouseExited(evt);
            }
        });

        minimizeLabel.setBackground(new Color(0, 0, 0));
        minimizeLabel.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        minimizeLabel.setForeground(new Color(255, 255, 255));
        minimizeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizeLabel.setText("-");
        minimizeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLabelMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeLabelMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout windowPanelLayout = new javax.swing.GroupLayout(windowPanel);
        windowPanel.setLayout(windowPanelLayout);
        windowPanelLayout.setHorizontalGroup(
                windowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(windowPanelLayout.createSequentialGroup()
                                .addGap(0, 24, Short.MAX_VALUE)
                                .addComponent(minimizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(exitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        windowPanelLayout.setVerticalGroup(
                windowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(windowPanelLayout.createSequentialGroup()
                                .addGroup(windowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(exitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(minimizeLabel))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(windowPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, -1, -1));

        signUpButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        signUpButton.setText("Înregistrează-te");
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });
        jPanel1.add(signUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 130, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new Color(255, 255, 255));
        jLabel4.setText("sau");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 320));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLabelMouseClicked

    private void exitLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseEntered
        exitLabel.setForeground(Color.RED);
    }//GEN-LAST:event_exitLabelMouseEntered

    private void exitLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseExited
        exitLabel.setForeground(Color.WHITE);
    }//GEN-LAST:event_exitLabelMouseExited

    private void minimizeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLabelMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minimizeLabelMouseClicked

    private void minimizeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLabelMouseEntered
        minimizeLabel.setForeground(new Color(49, 114, 178));
    }//GEN-LAST:event_minimizeLabelMouseEntered

    private void minimizeLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLabelMouseExited
        minimizeLabel.setForeground(Color.WHITE);
    }//GEN-LAST:event_minimizeLabelMouseExited

    int xx, xy;

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
        String user = usernameField.getText();
        String pass = String.valueOf(passwordField.getPassword());

        if (user == null || user.equals("") || user.contains(" ?!@#$^&./") || pass == null || pass.equals("") || user.length() < 5 || pass.length() < 5) {
            JOptionPane.showMessageDialog(this, "Username sau parola invalide!",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (CinemaGUIApplication.getContext().getBean(UserClient.class).existsByUsername(user, CasierGUI.getToken())) {
            JOptionPane.showMessageDialog(this, "Acest username este existent!",
                    "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            // User does not exist
            UserDto userDto = new UserDto(null, user, pass, UserRole.UNDEFINED);

            CinemaGUIApplication.getContext().getBean(UserClient.class).save(userDto, CasierGUI.getToken());
            JOptionPane.showMessageDialog(this, "V-ați înregistrat cu succes! Așteptați un administrator să va dea drepturi.",
                    "Succes", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_signUpButtonActionPerformed

    /* 1- admin 2-casier 3-user 4-undef */
    private void signInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInButtonActionPerformed
        MainGUI mainGUI = CinemaGUIApplication.getMainGUI();
        String user = usernameField.getText();
        String pass = String.valueOf(passwordField.getPassword());
        String token = CinemaGUIApplication.getContext().getBean(UserClient.class)
                .authenticate(user, pass);

        CasierGUI.setToken(token);
        mainGUI.getCurrentFrame().setVisible(false);
        mainGUI.setCurrentFrame(CasierGUI.getInstance());
        mainGUI.getCurrentFrame().setVisible(true);

        //TODO 404 not found
        //JOptionPane.showMessageDialog(MainGUI.currentFrame, "Invalid username or password.",
        //        "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_signInButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exitLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel minimizeLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton signInButton;
    private javax.swing.JButton signUpButton;
    private javax.swing.JTextField usernameField;
    private javax.swing.JPanel windowPanel;
    // End of variables declaration//GEN-END:variables
}
